/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package featurehub;

import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author daved
 */
public class FrmDashboard extends javax.swing.JFrame {
    private String username;
    private String role;
   
    /**
     * Creates new form DashboardFrame
     * @param username
     * @param role
     */
    public FrmDashboard(String username, String role) {
        initComponents();
        setTitle("Dashboard");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.username = username;
        this.role = role;
      
        lblUser.setText("Welcome, " + username);
        lblRole.setText("User Level: " + role);
        
        viewMenuPerRole(role);
        
        
        this.setLocationRelativeTo(null);
        // Create a timer that triggers every second (1000 milliseconds)
        // Create a timer that triggers every second (1000 milliseconds)
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                updateTime(); // Call the method to update the time
            }
        });
        timer.start(); // Start the timer
        // Initialize your components here, such as timeLabel
        
        timeLabel.setText("00-00-0000 00:00:00"); // Initial text

  
    }
    // Method to update the time
    private void updateTime() {
        Date currentDate = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        timeLabel.setText(dateFormat.format(currentDate)); // Update the time label
    }
    
    private void viewMenuPerRole(String role)
    {
        switch (role) {
            case "USER":
                btnVisualization.setVisible(false);
                btnEncryptDecrypt.setVisible(false);
                break;
            case "GUEST":
                btnQuiz.setVisible(false);
                btnChatbot.setVisible(false);
                break;
        }
    }

    FrmDashboard() {
        initComponents();
        setTitle("Dashboard");
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        btnQuiz = new javax.swing.JButton();
        btnVisualization = new javax.swing.JButton();
        btnChatbot = new javax.swing.JButton();
        btnEncryptDecrypt = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        btnCredits = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(49, 55, 62));

        timeLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(255, 255, 255));
        timeLabel.setText("timeLabel");

        lblUser.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Welcome, user!");

        btnQuiz.setBackground(new java.awt.Color(23, 155, 158));
        btnQuiz.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        btnQuiz.setForeground(new java.awt.Color(255, 255, 255));
        btnQuiz.setText("Take Quiz");
        btnQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuizActionPerformed(evt);
            }
        });

        btnVisualization.setBackground(new java.awt.Color(23, 155, 158));
        btnVisualization.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        btnVisualization.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualization.setText("<html><p align=\"center\"> Data<p/>Visualization</html>");
        btnVisualization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizationActionPerformed(evt);
            }
        });

        btnChatbot.setBackground(new java.awt.Color(96, 148, 26));
        btnChatbot.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        btnChatbot.setForeground(new java.awt.Color(255, 255, 255));
        btnChatbot.setText("<html><p align=\"center\">Simple</p> Chatbot</html>");
        btnChatbot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatbotActionPerformed(evt);
            }
        });

        btnEncryptDecrypt.setBackground(new java.awt.Color(96, 148, 26));
        btnEncryptDecrypt.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        btnEncryptDecrypt.setForeground(new java.awt.Color(255, 255, 255));
        btnEncryptDecrypt.setText("<html>Encryption <br> <p align=\"center\"> and </p> Decryption</html>");
        btnEncryptDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptDecryptActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(168, 46, 55));
        logoutButton.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Log out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        btnCredits.setBackground(new java.awt.Color(23, 155, 158));
        btnCredits.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        btnCredits.setForeground(new java.awt.Color(255, 255, 255));
        btnCredits.setText("Credits");
        btnCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FeatureHub");

        lblRole.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 255, 255));
        lblRole.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(timeLabel))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblUser)
                                .addGap(296, 296, 296)
                                .addComponent(lblRole))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnChatbot, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnVisualization, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEncryptDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLabel)
                    .addComponent(jLabel5))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(lblRole))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEncryptDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVisualization, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChatbot, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        dispose();
                new FrmLogin().setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void btnQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuizActionPerformed
       
        FrmQuiz frmquiz = new FrmQuiz(username, role); // Pass logged-in username
        frmquiz.setVisible(true);
        this.setVisible(false); // Hide the dashbo
    
    }//GEN-LAST:event_btnQuizActionPerformed

    private void btnChatbotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatbotActionPerformed
       
        FrmChatbot frmchatbot = new FrmChatbot (username, role);
        frmchatbot.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnChatbotActionPerformed

    private void btnVisualizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizationActionPerformed
        FrmVisualization frmvisuals = new FrmVisualization(username, role);
        frmvisuals.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVisualizationActionPerformed

    private void btnCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditsActionPerformed
       FrmCredits frmcredits = new FrmCredits(username, role);
       frmcredits.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnCreditsActionPerformed

    private void btnEncryptDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptDecryptActionPerformed
        // TODO add your handling code here:
        FrmEncryption form = new FrmEncryption(username, role);
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEncryptDecryptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChatbot;
    private javax.swing.JButton btnCredits;
    private javax.swing.JButton btnEncryptDecrypt;
    private javax.swing.JButton btnQuiz;
    private javax.swing.JButton btnVisualization;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUser;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
